# Generated by Django 5.1.4 on 2025-01-17 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthormodel',
            name='first_name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='first_name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='last_name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='last_name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogcommentmodel',
            name='blog',
            field=models.ForeignKey(default=2024, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blogmodel', verbose_name='blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogtagmodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blogtagmodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='blogauthormodel',
            name='avatar',
            field=models.ImageField(upload_to='blogs/authors/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='blogauthormodel',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='blogauthormodel',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='blogcategorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='blogs.blogcategorymodel', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='blogcategorymodel',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='blogcommentmodel',
            name='comment',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='blogcommentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='author',
            field=models.ManyToManyField(related_name='blogs', to='blogs.blogauthormodel', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='categories',
            field=models.ManyToManyField(related_name='blogs', to='blogs.blogcategorymodel', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(upload_to='blogs', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='blogtagmodel',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
    ]
