# Generated by Django 5.1.4 on 2025-01-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogauthormodel_first_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='blogs.blogtagmodel', verbose_name='tags'),
        ),
    ]
