# Generated by Django 5.1.4 on 2025-01-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthormodel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
