# Generated by Django 5.1.4 on 2025-01-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogauthormodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthormodel',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='description_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
