# Generated by Django 5.1.4 on 2025-01-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_colormodel_productsizemodel_producttagmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='color',
            new_name='colors',
        ),
        migrations.AddField(
            model_name='colormodel',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productsizemodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='size'),
        ),
        migrations.AddField(
            model_name='productsizemodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='size'),
        ),
        migrations.AddField(
            model_name='producttagmodel',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='producttagmodel',
            name='title_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='tag'),
        ),
    ]
