# Generated by Django 5.1.4 on 2025-01-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_color_productmodel_colors_colormodel_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='instock',
            field=models.BooleanField(default=False, verbose_name='instock'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='tags',
            field=models.ManyToManyField(related_name='product_tags', to='shop.producttagmodel', verbose_name='tag'),
        ),
    ]
