# Generated by Django 5.1.4 on 2025-01-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productmodel_instock_alter_productmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='instock',
            field=models.BooleanField(default=True, verbose_name='instock'),
        ),
    ]
