# Generated by Django 5.1.4 on 2025-01-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_name_colormodel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='shop.productcategorymodel', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='shop.colormodel', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sizes',
            field=models.ManyToManyField(related_name='products', to='shop.productsizemodel', verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='shop.producttagmodel', verbose_name='tag'),
        ),
    ]
